### PR TITLE
[iCubGenova02] fix spurious error at startup

### PR DESCRIPTION
**Pull request by traversaro**
Tested on the real robot and finally we got rid of the initial error,  see https://github.com/robotology/icub-main/issues/320 .

@randaz81 @barbalberto opening a PR just to make sure that I got https://github.com/robotology/icub-main/issues/320 correctly, feel free to merge if it seems fine.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/328%23issuecomment-216625105%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/328%23issuecomment-216625105%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22As%20mentioned%20in%20%23320%2C%20that%20parameter%20was%20intentionally%20removed%20to%20allow%20robot%20debugging.%20It%20will%20be%20added%20again%20in%20the%20near%20future.%22%2C%20%22created_at%22%3A%20%222016-05-03T18%3A40%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2869969%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/randaz81%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/328#issuecomment-216625105'>General Comment</a></b>
- <a href='https://github.com/randaz81'></a> As mentioned in #320, that parameter was intentionally removed to allow robot debugging. It will be added again in the near future.

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/328?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/328?approve=1'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/328'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/328'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by randaz81** [comment]
As mentioned in #320, that parameter was intentionally removed to allow robot debugging. It will be added again in the near future.

**Comment by traversaro** [comment]
I see, closing for now.

**Comment by pattacini** [comment]
@traversaro what's the idea behind this closed PR? If the aim is not to merge it, let's try to avoid keeping unnecessary branch in our beloved repo :wink:

**Comment by traversaro** [comment]
@pattacini Definitly! Apparently for some reason GitHub Pull Request interface for mobile phones does not have the "Delete Branch" button.

**Pull request closed without merging**
