### PR TITLE
Migrate functions using GSL to the new libYARP_gsl introduced in YARP 2.3.67.3

### PR DESCRIPTION
**Pull request by traversaro**
To be merged when https://github.com/robotology/yarp/pull/896 is merged.

### CODE REVIEW

**Comment by pattacini** [comment]
Merging this to ensure compatibility.

**Comment by pattacini** [comment]
@traversaro there are some tests failing here, but now we're out of sync with `yarp/devel`.

The failed tests are because of the correct yarp version is not found, I guess. Is it safe to merge it anyway?

**Comment by traversaro** [comment]
Yes. The problem is that travis dependencies script install `master`'s YARP, while this PR searches for YARP 2.3.67.3, i.e. the one with Eigen stuff merged.

This can be fixed (`icub-main` devel travis should get `yarp` devel) but I need to think how to do this right.

**Comment by pattacini** [comment]
In the meantime may we merge this?

**Comment by traversaro** [comment]
Yes.

**Pull request merged**
