### PR TITLE
fixed bug on Skin ports issue #235

### PR DESCRIPTION
**Pull request by giuliavezzani**
Introduced changes:
- closing skin ports that were remaining open : close function is now called inside threadRelease function
- threadRelease is  now called  only by RateThread, whereas before it was called twice

### CODE REVIEW

**Comment by pattacini** [comment]
The `close()` service needs to be called from outside the driver (as the `open()` method). The function `close()` does contain the call to `stop()` that in turn will call the `threadRelease()`. Thus, there's still something strange to be investigated.

**Comment by bhigy** [comment]
Would it be good if we call it from skinWrapper::close() (analogServer is belonging to skinWrapper)?

**Comment by barbalberto** [comment]
I see. Since the ``SkinWrapper`` directly calls the destructor, then the ``close()`` function was never called.

Can you check one thing please? Is the ``threadRelease()`` or ``close()`` called more then once by enabling env var YARP_TRACE_ENABLE=1?

Now that we (you) found the point, I believe the cleanest way is to have the destructor af analogServer simply call its own close function and move all the cleaning stuff there. maybe removing the explicit calls to threadRelease if it is redundant (it should be called by stop)

**Comment by pattacini** [comment]
In case the destructor will call the `close()`, we then make sure that calling `close()` twice in a row won't bring about any problem. This is because `close()` can be called also from outside the driver.

**Comment by barbalberto** [comment]
yes, that's true. SkinWrapper should definitely calls the close before the destructor.
Usually the desctructor should take care of cleaning things regardless of what happened in the past and not relyng on user code (close function called or not)

**Comment by barbalberto** [comment]
@pattacini yes, that's the correct behaviour. Close function can always be called more then once by the user so it must be safe in any case.

**Comment by bhigy** [comment]
One question regarding AnalogServer. The source file is in icub-main but it is part of yarp::dev namespace. Shouldn't it be in yarp repo?

**Comment by pattacini** [comment]
The inclusion of classes in `yarp::dev` outside `yarp` is at least misleading and confusing. It might be a leftover of the past and I cannot honestly foresee what will be the effect of removing that inclusion. Also, it is not the only driver doing so (see for example the `parametricCalibrator`).

Usually, the implementation of iCub specific drivers is located in `icub-main` repo.

Good catch anyways @bhigy

**Comment by barbalberto** [comment]
Most of the devices in icubmod are in the yarp::dev namespace. It's most probably a copy & paste leftover. One day we will fix it ... maybe next IFI day? :smile:

**Comment by giuliavezzani** [comment]
@bhigy  and me are thinking to put the close( ) of AnalogServer in its destructor to solve the problem. Is it necessary also to call it in the SkinWrapper, before the delete?
We also tried to call the close() function twice and it was ok.

**Comment by barbalberto** [comment]
Great work @bhigy and @giuliavezzani !!
Yes, I'll put the close also in the SkinWrapper, as good practise.

**Comment by pattacini** [comment]
Then, does everybody agree on merging this PR straightaway?

**Pull request merged**
