### PR TITLE
Added the POS service w/ mtb4fap

### PR DESCRIPTION
**Pull request by marcoaccame**
This PR improves the `POS` service so that we can now use also an `mtb4fap` board (and the `pmc`) and we can impose the calibration parameters in xml files.

See also https://github.com/robotology/icub-firmware-shared/pull/71

All was tested on a dedicated setup.

### CODE REVIEW

**Comment by pattacini** [comment]
Hi @marcoaccame 

Tonight, the [main CI also failed](https://github.com/robotology/icub-main/actions/runs/3239345511/jobs/5308612856) with the following errors:

```console
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parseService(yarp::os::Searchable&, servConfigPOS_t&)’:
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:[177](https://github.com/robotology/icub-main/actions/runs/3239345511/jobs/5308612856#step:14:178)1:25: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 1771 |     posBoardConfig_ptr->version.firmware.major = asServBoardInfo_ptr->firmware.major;
      |                         ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1772:25: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 1772 |     posBoardConfig_ptr->version.firmware.minor = asServBoardInfo_ptr->firmware.minor;
      |                         ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1773:25: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 1773 |     posBoardConfig_ptr->version.firmware.build = asServBoardInfo_ptr->firmware.build;
      |                         ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1774:25: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 1774 |     posBoardConfig_ptr->version.protocol.major = asServBoardInfo_ptr->protocol.major;
      |                         ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1775:25: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 1775 |     posBoardConfig_ptr->version.protocol.minor = asServBoardInfo_ptr->protocol.minor;
      |                         ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:[178](https://github.com/robotology/icub-main/actions/runs/3239345511/jobs/5308612856#step:14:179)8:29: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 1788 |         posBoardConfig_ptr->boardInfo.canloc[i].addr= sensor.location.can.addr;
      |                             ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1789:29: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 1789 |         posBoardConfig_ptr->boardInfo.canloc[i].port= sensor.location.can.port;
      |                             ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parseService(yarp::os::Searchable&, servConfigMC_t&)’:
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:3994:22: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 3994 |                 pos->boardInfo.canloc[i].port = mc_service.properties.poslocations[i].port;
      |                      ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:3995:22: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 3995 |                 pos->boardInfo.canloc[i].addr = mc_service.properties.poslocations[i].addr;
      |                      ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:3996:22: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 3996 |                 pos->boardInfo.canloc[i].insideindex = mc_service.properties.poslocations[i].insideindex;
      |                      ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4000:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4000 |             pos->version.firmware.major = mc_service.properties.canboards.at(0).firmware.major;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4001:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4001 |             pos->version.firmware.minor = mc_service.properties.canboards.at(0).firmware.minor;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4002:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4002 |             pos->version.firmware.build = mc_service.properties.canboards.at(0).firmware.build;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4003:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4003 |             pos->version.protocol.major = mc_service.properties.canboards.at(0).protocol.major;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4004:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4004 |             pos->version.protocol.minor = mc_service.properties.canboards.at(0).protocol.minor;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4045:22: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 4045 |                 pos->boardInfo.canloc[i].port = mc_service.properties.poslocations[i].port;
      |                      ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4046:22: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 4046 |                 pos->boardInfo.canloc[i].addr = mc_service.properties.poslocations[i].addr;
      |                      ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4047:22: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘boardInfo’
 4047 |                 pos->boardInfo.canloc[i].insideindex = mc_service.properties.poslocations[i].insideindex;
      |                      ^~~~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4051:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4051 |             pos->version.firmware.major = mc_service.properties.canboards.at(0).firmware.major;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4052:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4052 |             pos->version.firmware.minor = mc_service.properties.canboards.at(0).firmware.minor;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4053:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4053 |             pos->version.firmware.build = mc_service.properties.canboards.at(0).firmware.build;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4054:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4054 |             pos->version.protocol.major = mc_service.properties.canboards.at(0).protocol.major;
      |                  ^~~~~~~
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:4055:18: error: ‘struct eOmn_serv_config_data_as_pos_t’ has no member named ‘version’
 4055 |             pos->version.protocol.minor = mc_service.properties.canboards.at(0).protocol.minor;
```

The main CI downloads `icub-firmware@devel`, which already received the latest changes, so I reckon this is still related to this PR. Once the PR is merged, these errors should be gone, while we still need to fix the failure reported in the [OP](https://github.com/robotology/icub-main/pull/835#issue-1406418462).

**Comment by marcoaccame** [comment]
> Hi @marcoaccame
> 
> Tonight, the [main CI also failed](https://github.com/robotology/icub-main/actions/runs/3239345511/jobs/5308612856) with the following errors:
> 


I will check straight away.

**Comment by marcoaccame** [comment]
> Hi @marcoaccame
> 
> The CI fails with the following error:
> 
> ```shell
> /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parseService(yarp::os::Searchable&, servConfigPOS_t&)’:
> /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1901:55: error: ‘struct eoas_pos_SensorConfig_t’ has no member named ‘zero’
>  1901 |                 pos->config.boardconfig[b].sensors[s].zero = 0;
> ```

Hi @pattacini, I did some changes and I believe that now the CI will be OK.

**Comment by pattacini** [comment]
> Hi @pattacini, I did some changes and I believe that now the CI will be OK.

Great! I'll be just awaiting it to be complete and then happy to merge it.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
