### PR TITLE
[travis] On devel branch, get yarp devel

### PR DESCRIPTION
**Pull request by traversaro**
We should pay attention to this when merging `devel` to `master` for a release.
cc @drdanz @pattacini

### CODE REVIEW

**Comment by pattacini** [comment]
Yes definitely, and I bet we're gonna forget about that :wink:

**Comment by traversaro** [comment]
Marked [WIP] until https://github.com/robotology/yarp/pull/923 is merged.

**Comment by Tobias-Fischer** [comment]
Why don't you check the `$TRAVIS_BRANCH` environment variable? The easiest might be to do a `git checkout devel` for `yarp` whenever `$TRAVIS_BRANCH != "master"`.

**Comment by drdanz** [comment]
I'm not sure if checking `$TRAVIS_BRANCH != master` is ok... Any branch based on master will fail in this case.
IMO the best option is to have two different commits in the two branches so that a conflict is forced when we merge them and therefore we cannot forget about this.
Also the checkout is not really necessary, you can add `--branch devel` to the clone arguments... And BTW, in order to speed up the clone, I suggest to add `--depth 1` as well:

```
git clone --depth 1 --branch devel https://github.com/robotology/yarp
```

**Comment by drdanz** [comment]
And by the way, on `master` I think it would be better to clone the tag of the version required instead of the master branch...

**Comment by traversaro** [comment]
Just to avoid having this around: for the time being, the easiest solution is to checkout yarp devel and then (when we merge devel in master) go back to use yarp master, that at that point it will be compatible with icub-main devel again.  This is the easier solution and will have the nice side-effect that checking that icub-main remain compatible with the latest release of YARP, unless the compatibility is explicit disabled again by modifying `.travis.yml`.

**Comment by traversaro** [comment]
https://github.com/robotology/yarp/pull/923 was merged, starting the build again.

**Comment by traversaro** [comment]
Travis is working fine, I will merge unless someone objects.

**Pull request merged**
