### PR TITLE
[iCubDarmstadt01] modifications after CoDyCoY3

### PR DESCRIPTION
**Pull request by traversaro**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/338%23issuecomment-219039656%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/338%23issuecomment-219039656%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40randaz81%20If%20you%20want%20to%20briefly%20check%2C%20otherwise%20we%20will%20merge.%22%2C%20%22created_at%22%3A%20%222016-05-13T13%3A16%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/338#issuecomment-219039656'>General Comment</a></b>
- <a href='https://github.com/traversaro'></a> @randaz81 If you want to briefly check, otherwise we will merge.

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/338?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/338?approve=1'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/338'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/338'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by traversaro** [comment]
@randaz81 If you want to briefly check, otherwise we will merge.

**Comment by randaz81** [comment]
merged. Just for curiosity, you set Ki=0 position control because...?

**Comment by francesco-romano** [comment]
Because it causes (unstable)  oscillations on the robot while standing (making it falling)

**Pull request merged**
