### PR TITLE
Update filtering of spikes in temp reading

### PR DESCRIPTION
**Pull request by MSECode**
Completing the work done in https://github.com/robotology/icub-main/issues/959, the spikes in the temperature readings are 
now filtered by software.
This means that if the delta between current and previous temperature is higher than a threshold (which is currently defined in sw and by default is 20 Celsius degree) that new temperature read is considered as a spike and therefore, even if its value is higher than the `warning temperature threshold` or the `error temperature threshold`, it is discarded and not considered and the previous temperature is not updated.
Moreover, we have added to the `Watchdog` class a method for setting the threshold, regarding the maximum number of erroneous values read before sending error or warning, depending on the transmission rate of the ethernet packets.
Therefore, depending on the transmission rate defined in the configuration of the robot, we are setting the watchdogs for overcoming the warning threshold on the temperature reading and for overcoming the limit on the negative temperature values (which means that we got an error in the reading) so that it is always constant and independent to the transmission rate of the ethernet packets.
By default, it is set so that we rise the warning or error when we are getting erroneous temperature values (which are not spikes) for at least 60 seconds.

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Comment by S-Dafarra** [comment]
> By default, it is set so that we rise the warning or error when we are getting erroneous temperature values (which are not spikes) for at least 60 seconds.

Hi there, just as a curiosity. Is there a way to get these warnings from code?

**Comment by MSECode** [comment]
I'm not sure if I'm replying to what u need. Anyway, warnings are just related to reading a temperature higher than the warning threshold when that increment it is not a spike (where in this case a spike is defined when the delta between current and previous temperature is higher than 20 Celsius degree). Moreover, the first time temperature goes over the warning threshold a warning message is sent. Then, in order to not flooding the YRI, we send the next warning message if the temperature stays continuously above the threshold for at least 60 seconds. Timing definitions have been set here for now: https://github.com/robotology/icub-main/blob/5410ab082d5cf95109354e6cfd809a3324bc1d82/src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h#L111-L182
Instead, when you read negative readings, you check meaning of Celsius and Raw value in the error message from this table
https://icub-tech-iit.github.io/documentation/temperature_sensors/software/dataflow/#error-handling

**Comment by S-Dafarra** [comment]
I meant that if after 60s the joint goes in HF, I would love to have some warning before, that can be caught not just by reading at the YRI output (which is virtually impossible during experiments), but maybe via some API calls so that we can inform the user/controller accordingly.

**Comment by MSECode** [comment]
The HF is entirely managed by the 2FOC. This part in icub-main has been done to filter all the spikes that can happen due to noisy readings. Those parameters can be eventually adjusted depending on the need. 
Currently there are the APIs for retrieving the instantaneous value of temperature. We can think to even something else if necessary. Or it may be possible to update the module `motorTemperaturePublisher` to let it send advise to the user.
The idea of informing the low level controller can be problematic. We can think to inform the user, but in this case where should we send this "warning". What do u actually need for working fine? What should these APIs make to solve the problem? 
@valegagge, do you have some other ideas?

**Comment by S-Dafarra** [comment]
> The idea of informing the low level controller can be problematic

Just to clarify, I was referring more to a "high-level" controller, like the one controlling the walking.




> Or it may be possible to update the module `motorTemperaturePublisher` to let it send advise to the user.

I don't know about this since the ``motorTemperaturePublisher`` is not something that runs with the robot.



> We can think to inform the user, but in this case where should we send this "warning". What do u actually need for working fine? What should these APIs make to solve the problem?

Maybe a dedicated interface with a defined list of warning codes? I am pretty open to discussion here. Here some possible things I am imagining:
- the ``yarpmotorgui`` starts blinking on the joint that is about to fault
- a module starts making some noise, maybe also sending notifications to the OS (it is possible with QT, see https://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html)
- the walking controller goes in a fault safe configuration (maybe stopping the walking and going in a joint configuration that is safe in case of sudden HF)

**Comment by MSECode** [comment]
Oks, that's clear. Those points seem good. I'll discuss with the team about an implementation such that.

**Comment by valegagge** [comment]
Hi @S-Dafarra,
as we already discussed some time ago, the high-lever controller, such as the walking controller, should read the current motor temperature and compare it to the warning threshold. (Both information is available on IMotor interface). If the temperature exceeds the threshold should put the robot in a safe position or reduce the load on the motor with high temperature.

If I understand correctly, you are asking to signal in some way the warning state also on the `yarpmotorgui`.  

The work done in this PR had the purpose of avoiding `false-positive warning` to get a cleaner log.

**Comment by S-Dafarra** [comment]
> If I understand correctly, you are asking to signal in some way the warning state also on the `yarpmotorgui`.

I was referring to the case in which there are measurement errors for more than 60s. I was just wondering in which case, the user code can be informed about the potentially imminent fault.

**Comment by valegagge** [comment]
> > If I understand correctly, you are asking to signal in some way the warning state also on the `yarpmotorgui`.
> 
> I was referring to the case in which there are measurement errors for more than 60s. I was just wondering in which case, the user code can be informed about the potentially imminent fault.

The fault on error readings happens after 10 seconds. We had planned to fix the error reading issue by hardware. I'll update you ASAP. Stay tuned

**Pull request merged**
