### PR TITLE
Refactored due to upgrade to YARP-3.5 to deal with changes to `*Int`, `*Double`, `*Vocab` and to use the latest `yarp::conf` utilities

### PR DESCRIPTION
**Pull request by pattacini**
This PR proposes some refactoring inherited from:
- https://github.com/robotology/yarp/pull/2629
- https://github.com/robotology/yarp/pull/2650
- https://github.com/robotology/yarp/pull/2506

### CODE REVIEW

**Comment by pattacini** [comment]
@traversaro @Nicogene @marcoaccame this is a quite huge PR that mainly aims to check the CI with a full compilation.

**Review by Nicogene — APPROVED** [review]
I didn't go through all the files, but LGTM

**Comment by pattacini** [comment]
I'll merge the PR this afternoon.
@marcoaccame you could use the file-filtering features of the PR dashboards to display only `embo*` files.

**Comment by pattacini** [comment]
Just specify that now YARP-3.5.1 is required.

**Review by traversaro — APPROVED** [review]
I just gave an overview, but everything seems fine.

**Comment by pattacini** [comment]
Merging.
@marcoaccame you could check the content ex-post. In case, I'll fix any possible errors.

**Comment by marcoaccame** [comment]
> Merging.
> @marcoaccame you could check the content ex-post. In case, I'll fix any possible errors.

it seems ok.

**Pull request merged**
