### PR TITLE
[WIP] Fix bindings

### PR DESCRIPTION
**Pull request by Nicogene**
This PR should fix and clean icub bindings, it is incomplete, feel free to complete it and merge it when it is ready

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I changed the PR following the suggestions by @towardthesea and also did some other minor improvements. I was able to compile all bindings except of Ruby (as not installed on my machine), but did not test the bindings.

**Comment by Tobias-Fischer** [comment]
@towardthesea: Please approve the PR if all works fine for you
@pattacini / @drdanz: There were no changes to the bindings for a long time. Besides me, you were the last ones to change the bindings, so I marked you as potential reviewers. I think the PR can be safely merged, as currently the bindings are definitely broken and this PR can only improve the situation. Along with https://github.com/robotology/icub-main/pull/544 (which requires this PR to be merged), the bindings will be fixed + significantly improved.

**Comment by towardthesea** [comment]
I will re-check it whenever I have some time.

**Comment by towardthesea** [comment]
Hi @Tobias-Fischer ,
I have just tested the changes. 

**Good new first**: all languages can be compiled.
**Bad new**: Though it is possible to compile, I cannot import `icub` wrapper (for example in python). It turns out that my suggestions create `_icub.so` into the build folder `build/bindings/lib/python` while other files, e.g. `icubPYTHON_wrap.cxx`, `icubPYTHON_wrapp.h`, `icub.py` are still in `build/bindings`. I guess the same problems happen to other language. 

I can solve problem by adding this line (after `if(CREATE_PYTHON)`
```
set(CMAKE_SWIG_OUTDIR "${CMAKE_BINARY_DIR}/lib/python")
```
which apparently brings all generated files into the same folder with `_icub.so`, but I don't thing it is a clean solution. If you have any better way, please go ahead then let me know.

Cheers,
P

**Comment by Tobias-Fischer** [comment]
Hi @towardthesea,
Could you please check whether we can use something similar to what is being done in `icub-hri` regarding the output path of the Python libraries? Specifically, check https://github.com/robotology/icub-hri/blob/master/bindings/CMakeLists.txt and the way the output path is determined there. Also, it might be worth using the new cmake scripts to find Python 2 / 3.
Best, Tobi

**Comment by traversaro** [comment]
@towardthesea @Tobias-Fischer not directly related to this PR, but please be aware that CMake 3.12 has a renovated `UseSWIG.cmake` (https://cmake.org/cmake/help/v3.12/module/UseSWIG.html) module that probably would be useful. 
In particular this commit https://gitlab.kitware.com/cmake/cmake/commit/08f2a2408d1b5a4c5deff7deea4f923616fea717. combined with the proper use of  `target_include_directories` introduced in https://github.com/robotology/icub-main/pull/533 would avoid the need for all the `include_directories` calls. We probably cannot depend on CMake 3.12 until ~2020/2021, but it is probably worth to note, especially because in the past we already backported `UseSWIG` in YCM.

**Pull request merged**
