### PR TITLE
Added CLI options for change CAN ID and IP address

### PR DESCRIPTION
**Pull request by davidetome**
# New FirmwareUpdater CLI options
This PR introduces the `FirmwareUpdater CLI` capability to change : 

- CAN board ID via `SOCKETCAN` device
- CAN board ID via `ETH` device  
- IP address of an ETH board

## Change CAN ID via SOCKETCAN
In this example, we change the `CAN ID` on an `mtb` board connected via `SOCKETCAN` from 1 to 2.
The syntax of the command is the following : 
```bash
FirmwareUpdater -g -e SOCKETCAN -i 0 -c 0 -n 1 -k 2
```
where : 
- `-g -e SOCKETCAN -i 0 -c 0` is need to use a `SOCKETCAN` device (i.e. `ESD CAN/USB`) with `ID=0` and `canline=0`
- `-n 1 -k 2` changes old id 1 (-n 1) to 2 (-k 2)

https://user-images.githubusercontent.com/6638215/143570541-aab0d7ac-a9c9-45e3-b3c9-195622be5d4e.mp4

## Change CAN ID via ETH
In this example, we change the `CAN ID` on an `mtb` board connected via `ETH ` through an `ems4` board w/ `IP address = 10.0.1.1` from 1 to 2.
The syntax of the command is the following : 
```bash
FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -c 1 -n 1 -k 2
```
where : 
- `-g -e ETH -i eth1 -t 10.0.1.1 -c 1` is need to use a `ETH` device (i.e. `ems4`) with `ip address = 10.0.1.1` and `canline=1`
- `-n 1 -k 2` changes old id 1 (-n 1) to 2 (-k 2)

https://user-images.githubusercontent.com/6638215/143570871-71523cda-4d26-4433-823d-a89ba3fcaccc.mp4

## Change IP address of an ETH board
In this example, we change the `IP address on an `ems4` board from `10.0.1.1` to 110.0.1.21.
The syntax of the command is the following : 
```bash
 FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -2 10.0.1.2
```
where : 
- ` -g -e ETH -i eth1` is need to use a `ETH` device (i.e. `ems4`) 
- `-t 10.0.1.1 -2 10.0.1.2` changes old i`IP address` 10.0.1.1 to 10.0.1.2

https://user-images.githubusercontent.com/6638215/143571478-c2be1fb2-f357-4bc5-b3dd-e5539df0f555.mp4

cc @pattacini @maggia80 @emilianob80 @Uboldi80 @gsisinna @marcoaccame

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Awaiting the CI and the merge!
Thanks heaps @davidetome 👍🏻

**Comment by traversaro** [comment]
Not blocking at all, but it would be nice to have that the examples contained in the body of the PR could copied somewhere (even just https://github.com/robotology/icub-firmware-build/tree/master/docs, or in the README of firmwareupdater directory), otherwise we risk that they will be lost with the sands of time.

**Comment by davidetome** [comment]
Good idea @traversaro , just for completion, we may consider adding also the content of these PRs : 

- https://github.com/robotology/icub-main/pull/679
- https://github.com/robotology/icub-main/pull/682
- https://github.com/robotology/icub-main/pull/683

If you and @pattacini agree, I'll open an issue about that 👍🏻

**Comment by pattacini** [comment]
Yep, agreed @davidetome 👍🏻 
Let's use our internal workflow for this.

**Pull request merged**
