### PR TITLE
Add support for aea3 encoder 

### PR DESCRIPTION
**Pull request by sgiraz**
This PR introduces the support for the new AEA3 encoder.

The `ServiceParser` now recognize correctly the string for the new encoder.
A new `info` string will be printed when we run `yarprobotinterface` showing us with encoder we are trying to use.

**Note:** we should fix the defalut deadzone value for AEA3.

### CODE REVIEW

**Review by pattacini — CHANGES_REQUESTED** [review]
We should complete the work on the dead zone then.

**Comment by pattacini** [comment]
Hi @sgiraz 

CI failed with this error:

```console
2021-11-09T18:18:40.7393756Z /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parse_encoder_port(const string&, eObrd_ethtype_t, eOmc_encoder_t, uint8_t&, bool&)’:
2021-11-09T18:18:40.7397504Z /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1815:14: error: ‘eomc_enc_aea3’ was not declared in this scope; did you mean ‘eomc_enc_aea’?
```

Could you give it a look?

**Comment by sgiraz** [comment]
> Hi @sgiraz
> 
> CI failed with this error:
> 
> ```
> 2021-11-09T18:18:40.7393756Z /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parse_encoder_port(const string&, eObrd_ethtype_t, eOmc_encoder_t, uint8_t&, bool&)’:
> 2021-11-09T18:18:40.7397504Z /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1815:14: error: ‘eomc_enc_aea3’ was not declared in this scope; did you mean ‘eomc_enc_aea’?
> ```
> 
> Could you give it a look?

It is an expected failure because `eomc_enc_aea3` is included in `EoMotionControl.h` which is included in the new `icub-firmware-shared` which is waiting for approval in [PR](https://github.com/robotology/icub-firmware-shared/pull/50)

**Comment by pattacini** [comment]
Gotcha @sgiraz 👍🏻 
We can then re-run the CI once https://github.com/robotology/icub-firmware-shared/pull/50 will get merged.

**Review by Nicogene — APPROVED** [review]
I would bump the `icub_firmware_shared` version after the PR is merged and then I would increase the required version here in icub-main

**Comment by pattacini** [comment]
This is a good point @Nicogene.
I've already asked @marcoaccame to handle the versioning.

**Comment by marcoaccame** [comment]
> This is a good point @Nicogene. I've already asked @marcoaccame to handle the versioning.

The versioning is solved w/ the small change in icub-main done in [here](https://github.com/robotology/icub-main/pull/769/commits/4bf66c633ce2b1b1826a336ca54078f96f5aa87a), because of this [reason](https://github.com/robotology/icub-firmware-shared/pull/50#issuecomment-969964317).

**Review by pattacini — APPROVED** [review]
Thanks!

**Comment by pattacini** [comment]
Giving the CI the time to complete and then will merge it.

**Comment by marcoaccame** [comment]
> Gotcha @sgiraz 👍🏻 We can then re-run the CI once [robotology/icub-firmware-shared#50](https://github.com/robotology/icub-firmware-shared/pull/50) will get merged.

The CI will be 100% OK after the merge of the above PR.

**Pull request merged**
