### PR TITLE
Changes in skinManager configuration files

### PR DESCRIPTION
**Pull request by rustlluk**
This PR makes changes in configuration files for skinManager. It depends in on  #931 being merged, but it is created it as a separate PR as some changes may be debatable.

### Changes
 - skinManAll.ini now contains really everything, including legs and soles
 - skinManAllPlusLegs.ini and skinManAllPlusFoot.ini were deleted as they are redundant
 - new files for upper body and legs without soles were added
 - other files were updated with references to new soles and upper arm positions
   - also, the references to right/left_forearm_mesh.txt were changed to newer and more precise right/left_forearm_V2.txt 
 
 ### Tests
 All configs were tested on iCubPrague01
 
  @matejhof @BoPot

### CODE REVIEW

**Comment by pattacini** [comment]
Thanks @rustlluk for your contribution!
We will give it a whirl in the upcoming days on one of our robots before merging!

**Comment by pattacini** [comment]
Changed the base branch to `devel`.
@rustlluk can you check it again if everything is ok? It should be.

**Comment by rustlluk** [comment]
I dont see any commit in `devel` that could break anything, so should be fine.

**Comment by Nicogene** [comment]
Today I successfully tested these changes on `iCubGenova11`, except the (not fatal) errors on the legs (our robot does not have them) all the skin pipeline runs fine, @pattacini we can merge it!

**Pull request merged**
