### PR TITLE
Updated iCubHeidelberg configuration files

### PR DESCRIPTION
**Pull request by hu-yue**
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/hu-yue%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7060968%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/337%23issuecomment-217853209%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-09T12%3A40%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7060968%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/hu-yue%22%7D%7D%2C%20%7B%22body%22%3A%20%22Assuming%20you%27ve%20tested%20these%20modifications%20on%20the%20robot%2C%20I%27m%20going%20to%20merge%20the%20PR.%22%2C%20%22created_at%22%3A%20%222016-05-09T12%3A41%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/337%23issuecomment-217853209%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/337%23issuecomment-217853503%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/hu-yue'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/337#issuecomment-217853209'>General Comment</a></b>
- <a href='https://github.com/hu-yue'></a> :shipit:
- <a href='https://github.com/pattacini'></a> Assuming you've tested these modifications on the robot, I'm going to merge the PR.

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/337?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/337?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/337?approve=0'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/337'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/337'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by hu-yue** [comment]
:shipit:

**Comment by pattacini** [comment]
Assuming you've tested these modifications on the robot, I'm going to merge the PR.

**Comment by hu-yue** [comment]
:shipit:

**Comment by hu-yue** [comment]
:shipit:

**Comment by hu-yue** [comment]
:shipit:

**Pull request merged**
