### PR TITLE
Add GitHub Actions-based Continuous Integration

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by pattacini** [comment]
@traversaro I'm not quite sure why builds on Windows are failing. Inspecting the logs didn't highlight anything particular.

**Comment by traversaro** [comment]
There is somethink in ipopt include dirs not propagated correctly, I will check tommorow!

**Comment by traversaro** [comment]
The Windows build is failing as https://github.com/robotology/icub-main/commit/fb23cad205589180124b16145ddaa49288544743 was not committed in the master branch. As a release is imminent, I think it make sense to just target the `devel` branch.

**Comment by traversaro** [comment]
It is ok merging for me. Note that if you want to have a bit of reproducibility, it could make sense to switch the vcpkg installation to some fixed tag: otherwise any new commit on vcpkg could break our build (but that could be useful as we would catch vcpkg regression quite fast).

**Comment by pattacini** [comment]
Let's try first without any tagging for `vcpkg` and then we will iterate.

**Pull request merged**
