### PR TITLE
[icubCluster] Add icon

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Hi,

This small pull request adds an icon to `icub-cluster.py`, which makes it easier to find in the window list :).
The icon is from http://www.easyicon.net/language.en/31236-cluster_icon.html - maybe someone could contribute a prettier one.

Best,
Tobi
PS: I'm not sure who's best to handle this PR, maybe @lornat75?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/335%23issuecomment-217413829%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/335%23issuecomment-217798492%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/335%23issuecomment-217798522%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/335%23issuecomment-217798668%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/335%23issuecomment-217413829%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22PS%3A%20Code%20for%20setting%20the%20icon%20found%20on%20https%3A//stackoverflow.com/questions/11176638/python-setting-application-icon%22%2C%20%22created_at%22%3A%20%222016-05-06T11%3A15%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-09T07%3A52%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-09T07%3A52%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Tested%3A%20it%27s%20working%20nicely.%20Thanks%20for%20the%20add-in.%22%2C%20%22created_at%22%3A%20%222016-05-09T07%3A53%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/pattacini'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/335#issuecomment-217413829'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> PS: Code for setting the icon found on https://stackoverflow.com/questions/11176638/python-setting-application-icon
- <a href='https://github.com/pattacini'></a> :+1:
- <a href='https://github.com/pattacini'></a> :shipit:
- <a href='https://github.com/pattacini'></a> Tested: it's working nicely. Thanks for the add-in.

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/335?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/335?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/335?approve=0'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/335'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/335'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
PS: Code for setting the icon found on https://stackoverflow.com/questions/11176638/python-setting-application-icon

**Comment by pattacini** [comment]
:+1:

**Comment by pattacini** [comment]
:shipit:

**Comment by pattacini** [comment]
Tested: it's working nicely. Thanks for the add-in.

**Comment by pattacini** [comment]
:+1:

**Comment by alecive** [comment]
@pattacini @Tobias-Fischer I know that nobody cares (and I shouldn't care either, considering that I am not even using yarp any more right now), but I have the **urge** to propose a new icon for the cluster. Here are my suggestions:

 * https://github.com/alecive/FlatWoken/blob/master/FlatWoken/scalable/apps/computer.svg
 * https://github.com/alecive/FlatWoken/blob/master/FlatWoken/scalable/apps/computer_B.svg
 * https://github.com/alecive/FlatWoken/blob/master/FlatWoken/scalable/apps/server.svg (this is supposedly a server icon but it is nice anyway)

@Tobias-Fischer if your script does not like `svg` files, I can push them directly in `png` :)

**Comment by Tobias-Fischer** [comment]
@alecive: I vote for https://github.com/alecive/FlatWoken/blob/master/FlatWoken/scalable/apps/server.svg :).

I am not sure whether `svg` files are supported, but I don't think so. `png` should be easier. The file used so far is 128x128 pixels, maybe we can go for 256x256 instead.

Best,
Tobi

**Comment by lornat75** [comment]
@alecive since it looks like you have some spare time, would you mind having a lookt at reimplementing the icub-cluster in Qt for Linux and Windows? THAT would be very useful :)

**Comment by drdanz** [comment]
I think it would be also useful to have it in YARP, so that it can be used not only for iCub

**Comment by alecive** [comment]
@lornat75  eheh but it is not interesting :stuck_out_tongue: 

@Tobias-Fischer  I will commit the server icon in 256x256 then.

**Comment by alecive** [comment]
Done. Check it out! :+1:

**Comment by Tobias-Fischer** [comment]
Looking good thanks :)

**Comment by traversaro** [comment]
@alecive If you could suggest also an icon for the yarplogger it would be really appreciated. :D

**Comment by Tobias-Fischer** [comment]
@traversaro: I very briefly looked into having an icon for yarplogger, but I didn't find the proper place to put it within 5 minutes or so, so I gave up. An icon for that would definitely be great (any icon, really ..)!

**Comment by alecive** [comment]
@traversaro this is the one that I use in my iconset. Not really smart, but for a logger there are not many options:

https://github.com/alecive/FlatWoken/blob/a5de4003711fb0f35919588ca84949ac1f78f99e/FlatWoken/scalable/apps/search-log.svg

@Tobias-Fischer icons in the qt apps are usually handled by the `res.qrc` file (see e.g. the `yarpview` https://github.com/robotology/yarp/blob/master/src/yarpview-qt/src/res.qrc ) . Now, apparently @randaz81 is handling everything in that file a part from the logo eheh. 
What is currently the app icon? If there is no icon, I think you can set it by adding something like the following after the `windowTitle` property in `mainwindow.ui`:
```
  <property name="windowIcon">
   <iconset resource="res.qrc">
    <normaloff>:/images/logo.png</normaloff>:/images/logo.png</iconset>
  </property>
```

**Comment by Tobias-Fischer** [comment]
Hi @alecive,
Thanks for the hint. I'll have a look tomorrow afternoon or so, it looks fairly simple. Thanks!

**Comment by Tobias-Fischer** [comment]
It's done (yarplogger and yarpmotorgui). However I am struggling with push access rights to yarp, so stay tuned ..

**Comment by lornat75** [comment]
@Tobias-Fischer we have modified the policy for contributing to YARP, you can revise them here: http://www.yarp.it/md_.github_CONTRIBUTING.html

For such changes you can open a pull request.

**Comment by Tobias-Fischer** [comment]
@lornat75 I already opened one: https://github.com/robotology/yarp/pull/787 :)

**Pull request merged**
