### PR TITLE
FirmwareUpdater - Added new CLI options

### PR DESCRIPTION
**Pull request by davidetome**
# DESCRIPTION

This PR implements some new `CLI` options of the `FirmwareUpdater` tool; this need comes up from the new automated F/T sensor calibration procedure. 
Anyway, these commands can be used also for other purposes.

# DETAILS

The new `CLI` options implemented are : 

-   `-z` or `--load-dat-file` : Loads the calibration .dat file into  STRAIN2 eeprom (pass the file.dat with -l or --file option)
```
example : FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -c 1 -n 13 -z -l calibrationDataSN003.dat
```
-   `-w` or `--set-strain-sn <sn>` : Sets the passed serialNumber (i.e. SN001) on STRAIN2
```
example : FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -c 1 -n 13 -w SN001
```
- `-j` or ``--set-strain-gains`` :  Sets on STRAIN2 default gains to (8,24,24,10,10,24) , adjust the offset and check if some channel saturates
```
example : FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -c 1 -n 13 -j
```
- `-b` or `--get-canboard-version <saveFile>` :  Gets Bootloader or Application version (<saveFile> must be y or n to save or        not a file containing fw info)
```
example : FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -c 1 -n 13 -b y
```
- `-u` or `--save-dat-file` : Saves the calibration .dat file from STRAIN2 EEPROM
```
example : FirmwareUpdater -g -e ETH -i eth1 -t 10.0.1.1 -c 1 -n 13 -u
```

:information_source:  **All the example are running on a setup with an `EMS4` board with `IP=10.0.1.1` and a `STRAIN2` board attached to it in the `CAN1` line with `ID=13`**

## SCREENSHOT
image
----
cc @triccyx @simeonedussoni @julijenv @violadelbono @emilianob80 @maggia80 @MrAndrea @traversaro

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Thanks @davidetome for the very nice additions 🚀

**Comment by traversaro** [comment]
This is definitely something that should go in the next distro spotlight! @Nicogene  I think it should be nice to also put the nice docs that are part of the PR description somewhere more permanent, but I am not sure if there is any place where we can put them, possibily @marcoaccame has some suggestions on this.

**Comment by triccyx** [comment]
For me a double rocket for @davidetome !!

**Comment by simeonedussoni** [comment]
a mac-rocket menu, large 🥇 🍔 🤣

**Pull request merged**
