### PR TITLE
Place the definition file for skin error codes in dedicated directory at src/libraries/icubmod/skinLib

### LINKED ISSUE #81: Removing  the definition file for skin error codes from src/libraries/icubmod/motionControlLib.
This is raised in #80.

Possible solution is to move skin error codes from motionControlLib to firmwareShared.

@barbalberto, @randaz81, @JoErNanO

### PR DESCRIPTION
**Pull request by JoErNanO**
Fix #81.

The skin-related definition files are now in a newly created, and appropriately named, directory at `src/libraries/icubmod/skinLib`. Feel free to change this name if necessary.

@lornat75 @barbalberto

### CODE REVIEW

**Comment by lornat75** [comment]
@barbalberto is this patch safe to accept?

**Comment by barbalberto** [comment]
@JoErNanO : you can you also change the 
    src/libraries/icubmod/embObjLib/CMakeLists.txt 
by adding  "../skinLib" to the include_directories?
It fails the compilation otherwise,

Thank you

**Comment by JoErNanO** [comment]
@barbalberto Thanks for the heads-up. It's done in 9f5e6b1.

**Comment by barbalberto** [comment]
Ok, thank you for this cleaning.

**Pull request merged**
