### PR TITLE
[iCubGenova05] Fine calibration

### PR DESCRIPTION
**Pull request by traversaro**
Of legs, torso and head.
No fine calibration was performed of the arms,
except for the fix described in https://github.com/robotology/icub-support/issues/270 .

@randaz81 @davidetome can you check the modifications to the `calibration4`/`calibration5` parameters in `right_arm-calib.xml`? [1] 
I found these values on the robot .local and they seem to work well, but I don't know if they are correct or not. 

[1] :  https://github.com/robotology/icub-main/pull/357/files#diff-45e7af6bc262b6df0746365be8d6b9f2L24
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/357%23issuecomment-232349601%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/357%23issuecomment-232357848%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/357%23issuecomment-232358204%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/357%23issuecomment-232349601%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Any%20update%20on%20this%3F%22%2C%20%22created_at%22%3A%20%222016-07-13T13%3A10%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22ping%20%40randaz81%20%40davidetome%22%2C%20%22created_at%22%3A%20%222016-07-13T13%3A40%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%2C%20%7B%22body%22%3A%20%22Anyway%2C%20I%20think%20it%20is%20safe%20to%20merge%2C%20as%20the%20robot%20is%20working%20and%20calibrating%20fine.%20If%20there%20is%20anything%20wrong%20we%20can%20always%20fix%20it%20in%20the%20repo.%20%22%2C%20%22created_at%22%3A%20%222016-07-13T13%3A41%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/357#issuecomment-232349601'>General Comment</a></b>
- <a href='https://github.com/pattacini'></a> Any update on this?
- <a href='https://github.com/traversaro'></a> ping @randaz81 @davidetome
- <a href='https://github.com/traversaro'></a> Anyway, I think it is safe to merge, as the robot is working and calibrating fine. If there is anything wrong we can always fix it in the repo.

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/357?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/357?approve=1'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/357'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/357'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by pattacini** [comment]
Any update on this?

**Comment by traversaro** [comment]
ping @randaz81 @davidetome

**Comment by traversaro** [comment]
Anyway, I think it is safe to merge, as the robot is working and calibrating fine. If there is anything wrong we can always fix it in the repo.

**Pull request merged**
