### PR TITLE
EOMC::getTorque() uses remote value instaed of its local cached value

### PR DESCRIPTION
**Pull request by valegagge**
Now the device returns the torque value sent  periodically by embedded board.

### CODE REVIEW

**Comment by traversaro** [comment]
What was the effect on this? More traffic on the internal ethernet network than expected?

**Comment by valegagge** [comment]
The error seems due to 
`Error: Failed to download resource "qt"
Download failed: https://homebrew.bintray.com/bottles/qt-5.10.1.sierra.bottle.tar.gz
`
Can someone help me?
This PR is necessary to deliver a robot asap!

thanks

**Comment by traversaro** [comment]
The failure on Travis is not related with this PR, I think we can merge.

**Comment by marcoaccame** [comment]
ok also the new change: it removes the local write as it is not needed anymore.
thanks @valegagge

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
