### PR TITLE
[Calibrators] Fine calibration done for the Legs/Torso/Head

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
See http://wiki.icub.org/wiki/File:Fine_calibration.xls
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/364%23issuecomment-243176702%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/364%23issuecomment-243178849%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/364%23issuecomment-243176702%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Yeshasvitvs%20%40francesco-romano%20%40traversaro%20%5Cr%5CnWhat%20shall%20we%20do%20with%20this%20PR%3F%20Is%20it%20mergeable%3F%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-08-29T16%3A30%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yep%2C%20sorry%20I%20forgot%20to%20merge%21%20%22%2C%20%22created_at%22%3A%20%222016-08-29T16%3A38%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/traversaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/364#issuecomment-243176702'>General Comment</a></b>
- <a href='https://github.com/pattacini'></a> @Yeshasvitvs @francesco-romano @traversaro
What shall we do with this PR? Is it mergeable?
- <a href='https://github.com/traversaro'></a> Yep, sorry I forgot to merge!

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/364?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/364?approve=1'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/364'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/364'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by pattacini** [comment]
@Yeshasvitvs @francesco-romano @traversaro 
What shall we do with this PR? Is it mergeable?

**Comment by traversaro** [comment]
Yep, sorry I forgot to merge!

**Comment by Yeshasvitvs** [comment]
:+1:

**Pull request merged**
