### PR TITLE
[WIP] Multiple calib matrix

### PR DESCRIPTION
**Pull request by randaz81**
changes in canBusAnalogSensor and canLoader tool to allow use of multiple calibration matrices for F/T sensor (FW build >= 3.0.2)

### CODE REVIEW

**Comment by lornat75** [comment]
@barbalberto @traversaro

**Comment by traversaro** [comment]
+1

**Comment by randaz81** [comment]
final testing, do not merge yet

**Comment by randaz81** [comment]
status update @ 17/04/2015. This branch still requires additional checks before being merged.

**Comment by barbalberto** [comment]
@randaz81 This PR has conflict now, can you rebase it, please?

Thanks

**Comment by pattacini** [comment]
This is quite stale development (with conflicts).

I'm going to close this PR and delete the compare branch soon (I've safely stored a copy in https://github.com/robotology-legacy/icub-main-backup-19-07-2020) unless it'll receive attention asap.

**Pull request closed without merging**
