### PR TITLE
ethnamespace

### PR DESCRIPTION
**Pull request by marcoaccame**
cleaned the embobjlib. used a proper namespace (eth::) and uses a dedicated file for the main classes.

### CODE REVIEW

**Comment by marcoaccame** [comment]
Hi @traversaro, travis does not compile this branch because it retrieves YARP master and not  devel. Do you know how to make it use the correct branch? Thanks.

**Comment by traversaro** [comment]
@diegoferigo can you advise Marco on this? I am currently on the phone so it is tricky for me to answer to this!

**Comment by diegoferigo** [comment]
@traversaro I read this only now. @marcoaccame Yes at the current moment both `master` and `devel` branches of `icub-main` pull `yarp:master`. Beyond temporarily overriding the `.travis.yml` variable from the Travis web interface, this change would require some work / testing.

Considering that this could be a recurrent use case, what do you think @traversaro of using a keyword in the PR title (such as `[yarp-devel]`) and then parsing it from travis in order to pull `yarp:devel`?

**Comment by diegoferigo** [comment]
@marcoaccame Can you please rebase your `ethnamespace` branch on top of `devel`? Travis should work fine now.

**Pull request merged**
