### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by francesco-romano**
- Cleanup macOS dependencies installation
- Now YARP is cloned without history

Fixes https://github.com/robotology/icub-main/issues/470

@drdanz what about the GSL part? Is it still needed (see line 30)

### CODE REVIEW

**Comment by francesco-romano** [comment]
Todo before merging:
- [ ] brew complains that homebrew/science/opencv3 is deprecated 
- [ ] macOS builds still fail in the dependencies section

**Comment by francesco-romano** [comment]
Still failing. I think it is due to opencv  failing to install numpy.

**Comment by francesco-romano** [comment]
@drdanz the "original" issue (the one for which I opened this PR) is solved, but macOS builds are still failing.
We should cleanup a bit the dependencies section. 
What do we really need in order to compile `icub-main`?

**Comment by traversaro** [comment]
`gsl` is still a dependency of icub-main , so we just need to install it through brew (it used not to be necessary because gsl was a YARP dependency).

**Comment by francesco-romano** [comment]
I will add it.
What about `ode, gcc, goocanvas sdl sdl_gfx sdl_image` ?

**Comment by traversaro** [comment]
`ode` and `sdl` stuff are necessary for `iCub_SIM` (I don't know if it works on macOs at the moment, but for sure we are compiling it). I suspect goocanvas and gcc can be removed.

**Comment by traversaro** [comment]
I see that `ode` needs to be compiled from source. In that case it is probably better to omit it, and Travis will not build iCub_SIM .

**Comment by francesco-romano** [comment]
I think that at this point, it may worthwhile to solve https://github.com/robotology/homebrew-formulae/issues/3 before

**Comment by francesco-romano** [comment]
I discarded the idea of using the homebrew formula for icub-main as it would use the yarp formula.
In this case we have to separate travis between `macOS` and `linux`, also for the yarp installation.

Anyway, travis is now happy. I removed the allow_failures as now macOS compiles.
When travis finish, I will squash and merge.

**Pull request merged**
