### PR TITLE
Add the MAS client usage in WholeBodyDynamics

### PR DESCRIPTION
**Pull request by Nicogene**
Preface: I honestly don't know how the imu data is used in this module, i just kept the logic.

This PR add the possibility to make communicate the IMU and WholeBodyDynamics using the `multipleanalogsensorclient`.

cc @marcoaccame

### CODE REVIEW

**Comment by Nicogene** [comment]
I noticed that for `gravityCompensator` no changes are required. I get the inertial data reading form output streaming port of `wholeBodyDinamics`, not directly from the imu.

@traversaro correct me if I am wrong.

I added to this PR some cleanup commit of `gravityCompensator`.

**Comment by traversaro** [comment]
> @traversaro correct me if I am wrong.

Exactly, that is correct as far as I remember.

**Comment by Nicogene** [comment]
I added also the changes of in the `iCubGui` for using of MAS client since it was a small piece of code.

`wholeBodyDynamics`, `gravityCompensator` and `iCubGui` have now to be tested

**Comment by pattacini** [comment]
Let's go back to port-wise managing of the inertial done within the `iCubGui`.
Testing the functionality of WBD can be done via the combined use of `ARE` and `iCubGui`.

**Comment by Nicogene** [comment]
In the today meeting, emerged the necessity to connect the `iCubGui` to the inertial sensor at a later time and test it with the other modules involved in this PR.

TODO:
- [ ] Install the thrift of the `MultipleAnalogSensors` 
- [ ] Remove the instantiation of `multipleanalogsensorsclient` from `iCubGui`, it will read form the streaming port `measures:o` in order to not connect it at start time.
- [ ] Test `wholeBodyDynamics` with ARE
- [ ] Test `WBD` looking the forces in the `iCubGui` while moving the arms.

**Comment by pattacini** [comment]
@Nicogene any progress on this?

**Comment by Nicogene** [comment]
This PR depends by https://github.com/robotology/yarp/pull/2098, the minimum yarp version will be bumped.

**Comment by Nicogene** [comment]
The head v2.6 has been handled in this way in `iDyn`.
- 0467c47
- 9b1d4fa
- 897dabb

I know it is different to how the versioning is handled in `iKin`, actually `iKin` is somehow entangled with `iDyn`.
The best way should be add a constructor that accepts a `iKinChain` with a specified version in order to use only one versioning system. But for what I understood this library is still used only by few applications.

If I have green light @traversaro and @pattacini  I start testing `gravityCompensator` with the `imurfe`.

**Comment by pattacini** [comment]
🚦 green lights @Nicogene 👍 
As said, `iDyn` is quite old.

**Comment by Nicogene** [comment]
Today I tested successfully both WBD and `gravityCompensator`, checking the forces estimated in the `iCubGui` and trying the compliant mode on the arms.

It worked both with the classic imu and the imurfe.

Ready to be merged.

**Pull request merged**
