### PR TITLE
Fix bindings compilation from a clean directory

### PR DESCRIPTION
**Pull request by Nicogene**
This cleanup make possible to compile the bindings from a clean build.
In this sense I enabled it in the CI for see if now they works.

### CODE REVIEW

**Comment by traversaro** [comment]
Just to understand, why the GUI have been disabled in the CI?

**Comment by Nicogene** [comment]
> Just to understand, why the GUI have been disabled in the CI?

In order to speed-up the compilation, the YARP gui are not required for compiling `icub-main`(the icub guis are still compiled)

**Comment by Nicogene** [comment]
> Just to understand, why the GUI have been disabled in the CI?

In order to speed-up the compilation, the YARP gui are not required for compiling `icub-main`(the icub guis are still compiled)

**Comment by traversaro** [comment]
> 
> 
> > Just to understand, why the GUI have been disabled in the CI?
> 
> In order to speed-up the compilation, the YARP gui are not required for compiling `icub-main`(the icub guis are still compiled)

Ah yes, I erroneously thought you disabled the ICUB GUIs.

**Comment by traversaro** [comment]
To clarify, are you relying on using the `SWIG_USE_TARGET_INCLUDE_DIRECTORIES`  property? That is only available in CMake 3.13 .

**Comment by Nicogene** [comment]
> To clarify, are you relying on using the SWIG_USE_TARGET_INCLUDE_DIRECTORIES property? That is only available in CMake 3.13 .

It is not clear to me how swig behave with `target_include_directories`.
With `cmake 3.17.2` using `target_link_libraries` is sufficient to import the includes of the libraries linked, with `3.16` seems not.
For now I kept the explicit `include_directories`.

**Pull request merged**
