### PR TITLE
iCubCluster

### PR DESCRIPTION
**Pull request by drdanz**
* iCubCluster: Remove unused "type" option and references to yarpserver3. The "type" option is actually unused, and yarpserver3 will be soon removed from yarp (see robotology/yarp#780)

* icub-cluster-server.sh: Use memory instead /tmp for yarpserver portdb and and subdb. Memory should be faster. @lornat75 What do you think about this change?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225122399%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225350502%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225362462%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/350%23issuecomment-225122399%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20fine%20for%20me%2C%20maybe%20we%20can%20check%20with%20the%20users%20of%20the%20robot%20to%20see%20if%20they%20ever%20need%20to%20re-use%20the%20cache%20of%20the%20nameserver%3A%20%40pattacini%20%40vtikha%20%40randaz81%20%22%2C%20%22created_at%22%3A%20%222016-06-10T08%3A26%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1403333%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/lornat75%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40lornat75%20I%27ve%20never%20re-used%20the%20cache%2C%20actually.%5Cr%5CnFine%20with%20me.%22%2C%20%22created_at%22%3A%20%222016-06-11T10%3A24%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Actually%20I%20never%20used%20this%20feature...%22%2C%20%22created_at%22%3A%20%222016-06-11T13%3A40%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2869969%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/randaz81%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/350#issuecomment-225122399'>General Comment</a></b>
- <a href='https://github.com/lornat75'></a> Looks fine for me, maybe we can check with the users of the robot to see if they ever need to re-use the cache of the nameserver: @pattacini @vtikha @randaz81
- <a href='https://github.com/pattacini'></a> @lornat75 I've never re-used the cache, actually.
Fine with me.
- <a href='https://github.com/randaz81'></a> Actually I never used this feature...

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/350?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/350?approve=1'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/350'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/350'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by lornat75** [comment]
Looks fine for me, maybe we can check with the users of the robot to see if they ever need to re-use the cache of the nameserver: @pattacini @vtikha @randaz81

**Comment by pattacini** [comment]
@lornat75 I've never re-used the cache, actually.
Fine with me.

**Comment by randaz81** [comment]
Actually I never used this feature...

**Pull request merged**
