### PR TITLE
Fixed handling of temperature in MultipleFT service

### PR DESCRIPTION
**Pull request by triccyx**
Bug fix relating to temperature acquisition period for multiple FT sensor device

### CODE REVIEW

**Review by marcoaccame — APPROVED** [review]
I have tested the changes on my HW setup and now the rate of TX of temperature is correct

**Comment by traversaro** [comment]
Just to understand, what happened before this PR? I guess that period was parsed as seconds instead of milliseconds, so the temperature in existing boards that used `embObjMultipleFTsensors` was streamed only every 1000/60 = 16 minutes? Or there was something else mitigating this?

**Comment by triccyx** [comment]
> Just to understand, what happened before this PR? I guess that period was parsed as seconds instead of milliseconds, so the temperature in existing boards that used `embObjMultipleFTsensors` was streamed only every 1000/60 = 16 minutes? Or there was something else mitigating this?
> 
> fyi @HosameldinMohamed
Two things:
- Period read in msec but not correctly transformed in sec. For example, 10 msec in XML became 10 sec
- If you have used a period > 253 the period became always 253 (cast to uint8)

**Comment by traversaro** [comment]
Ack! So basically the temperature on the FT sensors of the foot of iCub3 (the only robot where `embObjMultipleFTsensors` is used at the moment) even if the .xml request 1000 (i.e. one seconds) was actually updated every 253 seconds, i.e. 4 minutes and 13 seconds.

**Pull request merged**
