### PR TITLE
adding support for mtb4c

### PR DESCRIPTION
**Pull request by davidetome**
This PR adds support for `mtb4c` boards

image

---

⚠️ Blocked by:
- https://github.com/robotology/icub-firmware-shared/pull/65

cc @marcoaccame @pattacini

### CODE REVIEW

**Review by pattacini — APPROVED** [review]

**Review by pattacini — CHANGES_REQUESTED** [review]
Hi @davidetome 

CI failed on ubuntu with the following error message:
```console
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parseService(yarp::os::Searchable&, servConfigSkin_t&)’:
/home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1642:196: error: ‘eobrd_cantype_mtb4c’ was not declared in this scope; did you mean ‘eobrd_cantype_mtb4w’?
 1642 |     if((eobrd_cantype_mtb != sk_service.properties.canboard.type) && (eobrd_cantype_mtb4 != sk_service.properties.canboard.type) && (eobrd_cantype_psc != sk_service.properties.canboard.type) && (eobrd_cantype_mtb4c != sk_service.properties.canboard.type))
      |                                                                                                                                                                                                    ^~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                                                    eobrd_cantype_mtb4w
make[2]: *** [src/libraries/icubmod/embObjLib/CMakeFiles/ethResources.dir/build.make:216: src/libraries/icubmod/embObjLib/CMakeFiles/ethResources.dir/serviceParser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3205: src/libraries/icubmod/embObjLib/CMakeFiles/ethResources.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Could you please give it a look?

**Comment by davidetome** [comment]
> Hi @davidetome
> 
> CI failed on ubuntu with the following error message:
> 
> ```
> /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp: In member function ‘bool ServiceParser::parseService(yarp::os::Searchable&, servConfigSkin_t&)’:
> /home/runner/work/icub-main/icub-main/src/libraries/icubmod/embObjLib/serviceParser.cpp:1642:196: error: ‘eobrd_cantype_mtb4c’ was not declared in this scope; did you mean ‘eobrd_cantype_mtb4w’?
>  1642 |     if((eobrd_cantype_mtb != sk_service.properties.canboard.type) && (eobrd_cantype_mtb4 != sk_service.properties.canboard.type) && (eobrd_cantype_psc != sk_service.properties.canboard.type) && (eobrd_cantype_mtb4c != sk_service.properties.canboard.type))
>       |                                                                                                                                                                                                    ^~~~~~~~~~~~~~~~~~~
>       |                                                                                                                                                                                                    eobrd_cantype_mtb4w
> make[2]: *** [src/libraries/icubmod/embObjLib/CMakeFiles/ethResources.dir/build.make:216: src/libraries/icubmod/embObjLib/CMakeFiles/ethResources.dir/serviceParser.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:3205: src/libraries/icubmod/embObjLib/CMakeFiles/ethResources.dir/all] Error 2
> make: *** [Makefile:146: all] Error 2
> ```
> 
> Could you please give it a look?

Ciao @pattacini , The error is due to this pending [PR](https://github.com/robotology/icub-firmware-shared/pull/65).
We should merge this once the other one is merged.

cc @marcoaccame

**Comment by pattacini** [comment]
Ok, so let's put this in draft (CI doesn't run for draft PR's).

**Review by pattacini — CHANGES_REQUESTED** [review]
Also, @davidetome, we're required to get aligned w/ the latest version of `icub-firmware-shared` (i.e., `1.26.1`) by editing the following file:

https://github.com/robotology/icub-main/blob/18a7cfc902d79ae9ddbf60fc5a6ad5607b1194cf/conf/iCubFindDependencies.cmake#L73-L78

**Comment by davidetome** [comment]
> Also, @davidetome, we're required to get aligned w/ the latest version of icub-firmware-shared (i.e., 1.26.1) 

@pattacini , done! Thanks! 👍🏻

**Review by pattacini — APPROVED** [review]
Waiting for the CI before merging.

**Pull request merged**
