### PR TITLE
[iCubLondon01] Fix various warnings

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Hi @randaz81,

This fixes various warnings when starting up `yarprobotinterface` on our robot. Could you please have a look whether it looks all fine to you and merge?

Thanks,
Tobi
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/icub-main/pull/334%23issuecomment-217221127%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/334%23issuecomment-217221367%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/334%23issuecomment-217613588%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/334%23issuecomment-217613611%22%2C%20%22https%3A//github.com/robotology/icub-main/pull/334%23issuecomment-217613613%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/icub-main/pull/334%23issuecomment-217221127%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22PS%3A%20There%20are%20still%20some%20warnings%20left%2C%20which%20can%20be%20partially%20fixed%20after%20https%3A//github.com/robotology/icub-main/issues/326%20has%20been%20fixed.%22%2C%20%22created_at%22%3A%20%222016-05-05T17%3A38%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22/cc%20%40gregoire-pointeau%20%40gsaponaro%20%40jypuigbo%20%22%2C%20%22created_at%22%3A%20%222016-05-05T17%3A38%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22To%20speed%20up%20and%20assuming%20that%20you%20already%20verified%20that%20these%20changes%20do%20work%2C%20I%27m%20merging%20this%20PR.%22%2C%20%22created_at%22%3A%20%222016-05-07T07%3A31%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-05-07T07%3A31%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-07T07%3A31%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/pattacini'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/icub-main/pull/334#issuecomment-217221127'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> PS: There are still some warnings left, which can be partially fixed after https://github.com/robotology/icub-main/issues/326 has been fixed.
- <a href='https://github.com/Tobias-Fischer'></a> /cc @gregoire-pointeau @gsaponaro @jypuigbo
- <a href='https://github.com/pattacini'></a> To speed up and assuming that you already verified that these changes do work, I'm merging this PR.

<a href='https://www.codereviewhub.com/robotology/icub-main/pull/334?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/334?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/icub-main/pull/334?approve=0'></a>&nbsp;<a href='https://github.com/robotology/icub-main/pull/334'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by drdanz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/icub-main/pull/334'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
PS: There are still some warnings left, which can be partially fixed after https://github.com/robotology/icub-main/issues/326 has been fixed.

**Comment by pattacini** [comment]
To speed up and assuming that you already verified that these changes do work, I'm merging this PR.

**Comment by pattacini** [comment]
:+1:

**Comment by pattacini** [comment]
:shipit:

**Comment by Tobias-Fischer** [comment]
Thanks for merging @pattacini :)

**Comment by randaz81** [comment]
Which are the remaining warnings?

**Comment by Tobias-Fischer** [comment]
There is still this warning left:
`WARNING Device left_arm_mc is not implementing a yarp::dev::IRemoteCalibrator, therefore it cannot attach to a Calibrator device` (because of https://github.com/robotology/icub-main/issues/326)

**Pull request merged**
