### PR TITLE
Can battery

### PR DESCRIPTION
**Pull request by triccyx**
Can battery new device
- Parser
- Device
- Test

### CODE REVIEW

**Comment by randaz81** [comment]
- I can see changes to internal lib, but what is the name of the device? 
- Does the device derives from the `yarp::dev::IBattery` public interface? (Please remember: `yarp::dev::IAnalogSensor` is going to be deprecated.)
- Can be used to read the charge/voltage/current from the battery on R1?

**Comment by triccyx** [comment]
@randaz81  
The xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE device PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd">


<device xmlns:xi="http://www.w3.org/2001/XInclude" name="battery" type="embObjBattery">

    <xi:include href="../../general.xml" />

    <xi:include href="../../hardware/electronics/face-eb22-j0_1-eln.xml" />

    <group name="SERVICE">

        <param name="type"> eomn_serv_AS_battery </param>

        <group name="PROPERTIES">

            <!-- we can have as many boards as we want, 
                 but now the only good ones are strain and strain2. 
                 use eoas_ft_isboardvalid() to verify -->
            <group name="CANBOARDS">
                <param name="type">                 bat      </param>

                <group name="PROTOCOL">
                    <param name="major">            0                   </param>
                    <param name="minor">            0                      </param>
                </group>
                <group name="FIRMWARE">
                    <param name="major">            0                   </param>
                    <param name="minor">            0                   </param>
                    <param name="build">            0                   </param>
                </group>
            </group>

            <group name="SENSORS">
                <param name="id">                   battery1        </param>
                <param name="board">                bat             </param>
                <param name="location">             CAN2:13         </param>
            </group>

        </group>

        <!-- we can pick up at max 4 sensors from the above list. 
             we can specify parameters which are different for each sensor 
             ft rate is in ms in range [1, 250]
             temperature rate is in ms but must be transformed in seconds.
             use calibration is boolean
             -->
        <group name="SETTINGS">
            <param name="enabledSensors">            battery1        </param>
            <param name="acquisitionRate">           1000            </param>   <!-- msec -->
        </group>


    </group>

</device>
```

**Comment by pattacini** [comment]
Hi @triccyx 

Remember that we need to make sure to compile against the new version of `icub-firmware-shared` as per https://github.com/robotology/icub-firmware-shared/pull/63.

**Comment by pattacini** [comment]
>Yes, I'm keeping the two repos aligned

The alignment needs to be enforced via cmake as per:

https://github.com/robotology/icub-main/blob/4e533b5d8499a2e5b346acbd22d1d50cbd422d0c/conf/iCubFindDependencies.cmake#L73-L78

**Comment by pattacini** [comment]
> > Yes, I'm keeping the two repos aligned
> 
> The alignment needs to be enforced via cmake as per:
> 
> https://github.com/robotology/icub-main/blob/4e533b5d8499a2e5b346acbd22d1d50cbd422d0c/conf/iCubFindDependencies.cmake#L73-L78

Hi @triccyx 
Remember to address this version constraint.

**Comment by pattacini** [comment]
Also, there are conflicts that need to be fixed, in particular, on this file:
`src/unittest/testServiceParserForMultipleFT.cpp`.

**Review by pattacini — COMMENTED** [review]
I'll keep this PR in draft until the sister PR in icub-firmware-shared will be merged.

**Review by pattacini — APPROVED** [review]
Waiting for CI and then I'll be happy to merge it.

**Pull request merged**
