### PR TITLE
Update embObjMotionControl and eomcParser to manage the new Kalman Filter paramenters

### PR DESCRIPTION
**Pull request by sgiraz**
What's new in this PR:

- `eomcParser` is now able to parse and manage the new Kalman Filter parameters from XML files: `kalmanFilterEnabled`, `x0`, `x1`, `x2`, `Q0`, `Q1`, `Q2`, `R` and `P0`. Here is an example (for one joint) of how they should be included in `hardware\motorControl\<board-joint>-mc.xml`

```xml
<group name="KALMAN_FILTER">
    <param name="kalmanFilterEnabled">          1                     </param>
    <param name="x0">                           0                     </param>
    <param name="x1">                           0                     </param>
    <param name="x2">                           0                     </param>
    <param name="Q0">                           0.0001                </param>
    <param name="Q1">                           0.01                  </param>
    <param name="Q2">                           10                    </param>
    <param name="R">                            0.0001                </param>
    <param name="P0">                           0.000099              </param>
</group>
```

**Note:**
- The integration has been tested on a custom single joint setup (mc4plus + DC motor + aea2) and iCubGenova02(🟣).

### CODE REVIEW

**Comment by sgiraz** [comment]
**Note:** This PR shouldn't be merged until `YARP 3.7` has been released

cc @pattacini

**Comment by pattacini** [comment]
CI has failed beacuse we need to merge https://github.com/robotology/icub-firmware-shared/pull/64 first.

cc @sgiraz

**Review by marcoaccame — APPROVED** [review]
ok

**Comment by pattacini** [comment]
Just awaiting the CI before merging.

**Pull request merged**
