### PR TITLE
Fingertip mk1.1 skinGui

### PR DESCRIPTION
**Pull request by simeonedussoni**
Added files for generating the skin GUI for mk1.1 fingertip aka FT2L/R with the revised taxel positions

### CODE REVIEW

**Review by pattacini — COMMENTED** [review]
Hi @simeonedussoni 

Just a note.
It seems that the file `right_hand_V2_2.ini` is missing in the PR.

Is it intended?

**Comment by simeonedussoni** [comment]
yes it is. I'll update it as soon as the assemblea ends.

**Review by pattacini — APPROVED** [review]
Ok, then.
Awaiting the CI to complete, before merging.

**Comment by simeonedussoni** [comment]
added `right_hand_V2_2.ini`

**Pull request merged**
