### PR TITLE
add strain2c

### PR DESCRIPTION
**Pull request by davidetome**
This PR adds support for the `strain2c` board.
Conflicts will be resolved under the supervision of @marcoaccame .

cc @pattacini @sgiraz

### CODE REVIEW

**Comment by pattacini** [comment]
Hi @davidetome 

The PR needs to be draft because it depends on `icub-firmware-shared`.
Also, there are conflicts we should resolve.

**Review by pattacini — CHANGES_REQUESTED** [review]
Changes requested.

**Comment by pattacini** [comment]
Hi @davidetome 

Please, don't put this PR in ready for review if the twin https://github.com/robotology/icub-firmware-shared/pull/72 is not merged yet, otherwise the CI will fail miserably 😉

**Review by marcoaccame — APPROVED** [review]
Hi @davidetome, the changes seems OK.

**Comment by pattacini** [comment]
Awaiting the CI.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
