### PR TITLE
FirmwareUpdater - configurable IPs

### PR DESCRIPTION
**Pull request by davidetome**
This PR allows configuring the IP's of the EMS boards through the `FirmwareUpdater` as per the request in https://github.com/robotology/QA/issues/423.

### CODE REVIEW

**Review by pattacini — APPROVED** [review]
Fine with me as we've tested it.
Probably, it's also worth awaiting @marcoaccame 's review.

**Review by Nicogene — APPROVED** [review]
Same from my side, maybe the debug messages can be removed

**Comment by davidetome** [comment]
> Same from my side, maybe the debug messages can be removed

I just added the message if the default ip is overwritten by the one in the config file; I think it is usefull...

**Comment by pattacini** [comment]
Hey @davidetome 

Next time it's better off devoting specific PR to specific developments. In this case, the changes implementing the CLI option would have best fitted a second PR.

Anyway, let's proceed this way. I'll only update the title of this PR to reflect its content.

**Review by marcoaccame — APPROVED** [review]
looks good to me.

**Pull request merged**
