### PR TITLE
Support OpenCV4

### LINKED ISSUE #634: Support compilation against OpenCV 4
I tried to compile icub-main with OpenCV 4, and this is the error message with icub-main: 
~~~
2020-01-13T16:59:39.2925890Z Scanning dependencies of target stereoCalib
2020-01-13T16:59:39.3277190Z [ 74%] Building CXX object src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/main.cpp.o
2020-01-13T16:59:41.9945860Z [ 74%] Building CXX object src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/stereoCalibModule.cpp.o
2020-01-13T16:59:44.6748180Z [ 74%] Building CXX object src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/stereoCalibThread.cpp.o
2020-01-13T16:59:46.4877660Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:190:80: error: use of undeclared identifier 'CV_CALIB_CB_ADAPTIVE_THRESH'; did you mean 'CALIB_CB_ADAPTIVE_THRESH'?
2020-01-13T16:59:46.4877920Z                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.4878060Z                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.4878170Z                                                                                CALIB_CB_ADAPTIVE_THRESH
2020-01-13T16:59:46.4881460Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:255:8: note: 'CALIB_CB_ADAPTIVE_THRESH' declared here
2020-01-13T16:59:46.4881600Z enum { CALIB_CB_ADAPTIVE_THRESH = 1,
2020-01-13T16:59:46.4881690Z        ^
2020-01-13T16:59:46.4882280Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:190:110: error: use of undeclared identifier 'CV_CALIB_CB_FAST_CHECK'; did you mean 'CALIB_CB_FAST_CHECK'?
2020-01-13T16:59:46.4882450Z                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.4882580Z                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.4883000Z                                                                                                              CALIB_CB_FAST_CHECK
2020-01-13T16:59:46.4883540Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:258:8: note: 'CALIB_CB_FAST_CHECK' declared here
2020-01-13T16:59:46.4883650Z        CALIB_CB_FAST_CHECK      = 8,
2020-01-13T16:59:46.4883730Z        ^
2020-01-13T16:59:46.4884350Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:190:135: error: use of undeclared identifier 'CV_CALIB_CB_NORMALIZE_IMAGE'; did you mean 'CALIB_CB_NORMALIZE_IMAGE'?
2020-01-13T16:59:46.4884480Z                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.4884610Z                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.4884710Z                                                                                                                                       CALIB_CB_NORMALIZE_IMAGE
2020-01-13T16:59:46.4885200Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:256:8: note: 'CALIB_CB_NORMALIZE_IMAGE' declared here
2020-01-13T16:59:46.4885300Z        CALIB_CB_NORMALIZE_IMAGE = 2,
2020-01-13T16:59:46.4885380Z        ^
2020-01-13T16:59:46.5302790Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:191:81: error: use of undeclared identifier 'CV_CALIB_CB_ADAPTIVE_THRESH'; did you mean 'CALIB_CB_ADAPTIVE_THRESH'?
2020-01-13T16:59:46.5303450Z                     foundR = findChessboardCorners(Right, boardSize, pointbufR, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.5303580Z                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.5303670Z                                                                                 CALIB_CB_ADAPTIVE_THRESH
2020-01-13T16:59:46.5304200Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:255:8: note: 'CALIB_CB_ADAPTIVE_THRESH' declared here
2020-01-13T16:59:46.5304310Z enum { CALIB_CB_ADAPTIVE_THRESH = 1,
2020-01-13T16:59:46.5304390Z        ^
2020-01-13T16:59:46.5304930Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:191:111: error: use of undeclared identifier 'CV_CALIB_CB_FAST_CHECK'; did you mean 'CALIB_CB_FAST_CHECK'?
2020-01-13T16:59:46.5305070Z                     foundR = findChessboardCorners(Right, boardSize, pointbufR, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.5305320Z                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.5305420Z                                                                                                               CALIB_CB_FAST_CHECK
2020-01-13T16:59:46.5305900Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:258:8: note: 'CALIB_CB_FAST_CHECK' declared here
2020-01-13T16:59:46.5306000Z        CALIB_CB_FAST_CHECK      = 8,
2020-01-13T16:59:46.5306060Z        ^
2020-01-13T16:59:46.5306610Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:191:136: error: use of undeclared identifier 'CV_CALIB_CB_NORMALIZE_IMAGE'; did you mean 'CALIB_CB_NORMALIZE_IMAGE'?
2020-01-13T16:59:46.5306750Z                     foundR = findChessboardCorners(Right, boardSize, pointbufR, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.5307040Z                                                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.5307170Z                                                                                                                                        CALIB_CB_NORMALIZE_IMAGE
2020-01-13T16:59:46.5307710Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:256:8: note: 'CALIB_CB_NORMALIZE_IMAGE' declared here
2020-01-13T16:59:46.5307800Z        CALIB_CB_NORMALIZE_IMAGE = 2,
2020-01-13T16:59:46.5307870Z        ^
2020-01-13T16:59:46.5778150Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:312:80: error: use of undeclared identifier 'CV_CALIB_CB_ADAPTIVE_THRESH'; did you mean 'CALIB_CB_ADAPTIVE_THRESH'?
2020-01-13T16:59:46.5778450Z                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.5778630Z                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.5778730Z                                                                                CALIB_CB_ADAPTIVE_THRESH
2020-01-13T16:59:46.5779300Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:255:8: note: 'CALIB_CB_ADAPTIVE_THRESH' declared here
2020-01-13T16:59:46.5779630Z enum { CALIB_CB_ADAPTIVE_THRESH = 1,
2020-01-13T16:59:46.5789830Z        ^
2020-01-13T16:59:46.5790750Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:312:110: error: use of undeclared identifier 'CV_CALIB_CB_FAST_CHECK'; did you mean 'CALIB_CB_FAST_CHECK'?
2020-01-13T16:59:46.5791360Z                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.5791470Z                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.5791580Z                                                                                                              CALIB_CB_FAST_CHECK
2020-01-13T16:59:46.5792140Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:258:8: note: 'CALIB_CB_FAST_CHECK' declared here
2020-01-13T16:59:46.5792240Z        CALIB_CB_FAST_CHECK      = 8,
2020-01-13T16:59:46.5792310Z        ^
2020-01-13T16:59:46.5792890Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:312:135: error: use of undeclared identifier 'CV_CALIB_CB_NORMALIZE_IMAGE'; did you mean 'CALIB_CB_NORMALIZE_IMAGE'?
2020-01-13T16:59:46.5793040Z                     foundL = findChessboardCorners(Left, boardSize, pointbufL, CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.5793160Z                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.5793270Z                                                                                                                                       CALIB_CB_NORMALIZE_IMAGE
2020-01-13T16:59:46.5793750Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:256:8: note: 'CALIB_CB_NORMALIZE_IMAGE' declared here
2020-01-13T16:59:46.5793850Z        CALIB_CB_NORMALIZE_IMAGE = 2,
2020-01-13T16:59:46.5793920Z        ^
2020-01-13T16:59:46.6458220Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:628:45: error: use of undeclared identifier 'CV_CALIB_CB_ADAPTIVE_THRESH'; did you mean 'CALIB_CB_ADAPTIVE_THRESH'?
2020-01-13T16:59:46.6458860Z                                             CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.6458990Z                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.6459090Z                                             CALIB_CB_ADAPTIVE_THRESH
2020-01-13T16:59:46.6459650Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:255:8: note: 'CALIB_CB_ADAPTIVE_THRESH' declared here
2020-01-13T16:59:46.6459760Z enum { CALIB_CB_ADAPTIVE_THRESH = 1,
2020-01-13T16:59:46.6459830Z        ^
2020-01-13T16:59:46.6460400Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:628:75: error: use of undeclared identifier 'CV_CALIB_CB_FAST_CHECK'; did you mean 'CALIB_CB_FAST_CHECK'?
2020-01-13T16:59:46.6460580Z                                             CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.6460680Z                                                                           ^~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.6460780Z                                                                           CALIB_CB_FAST_CHECK
2020-01-13T16:59:46.6461260Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:258:8: note: 'CALIB_CB_FAST_CHECK' declared here
2020-01-13T16:59:46.6461370Z        CALIB_CB_FAST_CHECK      = 8,
2020-01-13T16:59:46.6461450Z        ^
2020-01-13T16:59:46.6462020Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:628:100: error: use of undeclared identifier 'CV_CALIB_CB_NORMALIZE_IMAGE'; did you mean 'CALIB_CB_NORMALIZE_IMAGE'?
2020-01-13T16:59:46.6462370Z                                             CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_FAST_CHECK | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.6462460Z                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.6462570Z                                                                                                    CALIB_CB_NORMALIZE_IMAGE
2020-01-13T16:59:46.6463100Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:256:8: note: 'CALIB_CB_NORMALIZE_IMAGE' declared here
2020-01-13T16:59:46.6463200Z        CALIB_CB_NORMALIZE_IMAGE = 2,
2020-01-13T16:59:46.6463280Z        ^
2020-01-13T16:59:46.6619530Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:643:17: error: use of undeclared identifier 'CV_CALIB_FIX_ASPECT_RATIO'; did you mean 'CALIB_FIX_ASPECT_RATIO'?
2020-01-13T16:59:46.6619780Z     if( flags & CV_CALIB_FIX_ASPECT_RATIO )
2020-01-13T16:59:46.6619900Z                 ^~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.6619980Z                 CALIB_FIX_ASPECT_RATIO
2020-01-13T16:59:46.6620490Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:270:8: note: 'CALIB_FIX_ASPECT_RATIO' declared here
2020-01-13T16:59:46.6620590Z        CALIB_FIX_ASPECT_RATIO    = 0x00002,
2020-01-13T16:59:46.6620660Z        ^
2020-01-13T16:59:46.6803700Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:653:40: error: use of undeclared identifier 'CV_CALIB_FIX_K3'; did you mean 'CALIB_FIX_K3'?
2020-01-13T16:59:46.6803920Z                     Dist, rvecs, tvecs,CV_CALIB_FIX_K3);
2020-01-13T16:59:46.6804010Z                                        ^~~~~~~~~~~~~~~
2020-01-13T16:59:46.6804080Z                                        CALIB_FIX_K3
2020-01-13T16:59:46.6804580Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:276:8: note: 'CALIB_FIX_K3' declared here
2020-01-13T16:59:46.6804710Z        CALIB_FIX_K3              = 0x00080,
2020-01-13T16:59:46.6804790Z        ^
2020-01-13T16:59:46.7122340Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:714:51: error: use of undeclared identifier 'CV_CALIB_CB_ADAPTIVE_THRESH'; did you mean 'CALIB_CB_ADAPTIVE_THRESH'?
2020-01-13T16:59:46.7122770Z                                                   CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.7122880Z                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.7122960Z                                                   CALIB_CB_ADAPTIVE_THRESH
2020-01-13T16:59:46.7123720Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:255:8: note: 'CALIB_CB_ADAPTIVE_THRESH' declared here
2020-01-13T16:59:46.7123840Z enum { CALIB_CB_ADAPTIVE_THRESH = 1,
2020-01-13T16:59:46.7123930Z        ^
2020-01-13T16:59:46.7124630Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:714:81: error: use of undeclared identifier 'CV_CALIB_CB_NORMALIZE_IMAGE'; did you mean 'CALIB_CB_NORMALIZE_IMAGE'?
2020-01-13T16:59:46.7124750Z                                                   CV_CALIB_CB_ADAPTIVE_THRESH | CV_CALIB_CB_NORMALIZE_IMAGE);
2020-01-13T16:59:46.7124850Z                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.7124950Z                                                                                 CALIB_CB_NORMALIZE_IMAGE
2020-01-13T16:59:46.7125480Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:256:8: note: 'CALIB_CB_NORMALIZE_IMAGE' declared here
2020-01-13T16:59:46.7125580Z        CALIB_CB_NORMALIZE_IMAGE = 2,
2020-01-13T16:59:46.7125650Z        ^
2020-01-13T16:59:46.7730350Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:767:25: error: use of undeclared identifier 'CV_CALIB_FIX_ASPECT_RATIO'; did you mean 'CALIB_FIX_ASPECT_RATIO'?
2020-01-13T16:59:46.7730740Z                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
2020-01-13T16:59:46.7730830Z                         ^~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.7730910Z                         CALIB_FIX_ASPECT_RATIO
2020-01-13T16:59:46.7731440Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:270:8: note: 'CALIB_FIX_ASPECT_RATIO' declared here
2020-01-13T16:59:46.7731540Z        CALIB_FIX_ASPECT_RATIO    = 0x00002,
2020-01-13T16:59:46.7731620Z        ^
2020-01-13T16:59:46.7732170Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:767:53: error: use of undeclared identifier 'CV_CALIB_ZERO_TANGENT_DIST'; did you mean 'CALIB_ZERO_TANGENT_DIST'?
2020-01-13T16:59:46.7732300Z                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
2020-01-13T16:59:46.7732380Z                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.7732470Z                                                     CALIB_ZERO_TANGENT_DIST
2020-01-13T16:59:46.7732930Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:272:8: note: 'CALIB_ZERO_TANGENT_DIST' declared here
2020-01-13T16:59:46.7733030Z        CALIB_ZERO_TANGENT_DIST   = 0x00008,
2020-01-13T16:59:46.7733100Z        ^
2020-01-13T16:59:46.7733800Z /Users/runner/runners/2.163.1/work/robotology-superbuild/robotology-superbuild/robotology/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:767:82: error: use of undeclared identifier 'CV_CALIB_SAME_FOCAL_LENGTH'; did you mean 'CALIB_SAME_FOCAL_LENGTH'?
2020-01-13T16:59:46.7733960Z                         CV_CALIB_FIX_ASPECT_RATIO + CV_CALIB_ZERO_TANGENT_DIST + CV_CALIB_SAME_FOCAL_LENGTH + CV_CALIB_FIX_K3,
2020-01-13T16:59:46.7734060Z                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-13T16:59:46.7734520Z                                                                                  CALIB_SAME_FOCAL_LENGTH
2020-01-13T16:59:46.7735070Z /usr/local/Cellar/opencv/4.2.0_1/include/opencv4/opencv2/calib3d.hpp:289:8: note: 'CALIB_SAME_FOCAL_LENGTH' declared here
2020-01-13T16:59:46.7735160Z        CALIB_SAME_FOCAL_LENGTH   = 0x00200,
2020-01-13T16:59:46.7735240Z        ^
2020-01-13T16:59:46.7735640Z fatal error: too many errors emitted, stopping now [-ferror-limit=]
2020-01-13T16:59:46.7852270Z 20 errors generated.
2020-01-13T16:59:46.7948790Z make[5]: *** [src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/stereoCalibThread.cpp.o] Error 1
2020-01-13T16:59:46.7956150Z make[4]: *** [src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/all] Error 2
2020-01-13T16:59:46.7963400Z make[3]: *** [all] Error 2
2020-01-13T16:59:46.7978370Z make[2]: *** [robotology/ICUB/CMakeFiles/YCMStamp/ICUB-build] Error 2
2020-01-13T16:59:46.7981270Z make[1]: *** [CMakeFiles/ICUB.dir/all] Error 2
2020-01-13T16:59:46.7989190Z make: *** [all] Error 2
2020-01-13T16:59:46.8018810Z ##[error]Process completed with exit code 2.
2020-01-13T16:59:46.8107470Z Cleaning up orphan processes
~~~

### PR DESCRIPTION
**Pull request by Nicogene**
This PR drops the support of OpenCV 2 and add the support to OpenCV 4.

TODO:

- [x] Compile with `opencv` 3.
- [x] Compile with `opencv` 4.
- [x] Test `camCalib`s.

It fixes #634

### CODE REVIEW

**Comment by Nicogene** [comment]
I successfully tested `camCalib` on `iCubGenova01`.
The changes are **identical** also in other "calibs" module since they share some copy-paste code.
If you think that it is a sufficient test I would merge.

it compiles both with opencv 3 and 4.

**Comment by pattacini** [comment]
Superb 🚀

**Comment by Nicogene** [comment]
The windows build is stuck, since the macOs(opencv 4) and ubuntu(opencv 3) passed, I will merge anyway

**Comment by pattacini** [comment]
It's not stuck, it's just taking much longer for building the dependencies 😉

**Pull request merged**
