### PR TITLE
Cleanup of warnings related to YarpPlugin.cmake cmake functions

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by pattacini** [comment]
Just **rebased** on `devel` (be careful @traversaro) and tested.

I'm not particularly into it but it's working fine. I think we can accept the PR.

cc @drdanz @traversaro

**Comment by traversaro** [comment]
The PR was against `master`? Sorry, I must have forget to change that. 
It was just a cleanup that I started as a workaround against https://github.com/robotology/yarp/issues/916 , but given that it was something that eventually we needed to do I went on an did it on all the repo.

**Comment by pattacini** [comment]
Don't worry, the PR is on `devel`. I just wanted to warn you that I `git push --force` the branch rebased over `devel` for me to test it.

**Comment by pattacini** [comment]
Tested on a separated repo (haptic-devices). It's working fine, merging.

**Pull request merged**
