### PR TITLE
New position files for soles and upper arms

### PR DESCRIPTION
**Pull request by rustlluk**
This PR adds position files for the skin on left/right soles and upper arms.

### How the files were created
 - soles:  
   - centers of triangles extracted from [URDF model](https://github.com/robotology/icub-models/blob/master/iCub/robots/iCubGazeboV2_7/model.urdf)  
 - upper arms:
   - centers of triangles extracted from CAD models of the skin mounts 
 - other taxels are "flat" around it 
 - the triangles are rotated along the Z-axis to fit the orientation on the real robot  
 - the positions are specified w.r.t. URDF frames specified in the files (l/r_foot and l/r_upper_arm)
 
### Tests
 - local positions w.r.t. local frames were tested by manually poking individual taxels on iCubPrague01
 - global position were tested by loading URDF of the robot in a simulator and moving the skin together with its corresponding frame
 
 @matejhof @BoPot

### CODE REVIEW

**Review by simeonedussoni — APPROVED** [review]
Hi @rustlluk 
the PR looks pretty good. It would be very nice to have a couple screenshots showing the robot with the applied taxels for visual reference. Can you provide this?

**Review by pattacini — APPROVED** [review]
This PR can be merged straight away.

>It would be very nice to have a couple screenshots showing the robot with the applied taxels for visual reference. Can you provide this?

I concur with @simeonedussoni. It'd be nice to have them before merging.

**Comment by rustlluk** [comment]
Sure, not problem. 
I tried to capture everything, but can add more if needed
| Screenshot from 2024-01-12 10-41-49 | Screenshot from 2024-01-12 10-41-58 |  
| --- | --- | 
| Screenshot from 2024-01-12 10-42-09 | Screenshot from 2024-01-12 10-42-23 |

**Comment by pattacini** [comment]
Thanks heaps! Look nice!

Merging in `devel` rather than `master`.

**Pull request merged**
