### PR TITLE
Cleanup of Win EOL.

### PR DESCRIPTION
**Pull request by Nicogene**
Command used: `for f in $(git ls-files); do dos2unix $f; done`

### CODE REVIEW

**Comment by pattacini** [comment]
Not really in favor of this.

**Comment by pattacini** [comment]
This PR proposes modifications that are environment-dependent and there's no guarantee that we won't generate in the future further changes not in accordance with this policy.

I'm going to close this.

**Comment by drdanz** [comment]
@pattacini that's nonsense, you don't want files stored using windows EOL on your repository, unless you choose to have all of them stored using windows EOL (with the exception of windows-specific files). This is just going to complicate the life of programmers (both on linux and windows).
I'm in favour of reopening and merging this PR immediately.

**Comment by drdanz** [comment]
See also https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by pattacini** [comment]
@drdanz I'm perfectly aware of the context behind this PR and I talked offline with @Nicogene about it. My closing comment occurred after this chat and aimed to leave a very brief motivation, which you're not taking as a good explanation, but this is another story. 

The same happened for PR #642.

**Pull request closed without merging**
